<a href="https://colab.research.google.com/github/1nf1n1tee/CSE_425-Neural-Networks/blob/main/CNN_From_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [35]:
rows_a = 5 #@param {type:"integer"}
cols_a = 5 #@param {type:"integer"}
rows_b = 5 #@param {type:"integer"}
cols_b = 5 #@param {type:"integer"}

a = np.random.randint(0, 1, size=(rows_a, cols_a))
b = np.random.randint(0, 100, size=(rows_b, cols_b))

print("Matrix a:\n", a)
print("Matrix a:\n", a[0:3,0:3])
print("\nMatrix b:\n", b)


Matrix a:
 [[83 80 36 45 58]
 [91 73 24 84 69]
 [98 91 76 37 42]
 [96 53 30 11 74]
 [77 32 14 51 81]]
Matrix a:
 [[83 80 36]
 [91 73 24]
 [98 91 76]]

Matrix b:
 [[23 85 13 42 87]
 [51 34 54 75 38]
 [52 25 59 82 88]
 [35 21 68 30 17]
 [18 99 64 23 33]]


In [49]:
def conv(matrix, filter, stride):

  matrix_rows, matrix_cols = matrix.shape
  filter_rows, filter_cols = filter.shape

  output_rows = (matrix_rows - filter_rows) // stride + 1
  output_cols = (matrix_cols - filter_cols) // stride + 1
  output = np.zeros((output_rows, output_cols))

  for i in range(0,output_rows,stride):
    for j in range(0,output_cols,stride):
      region = matrix[i:i+filter_rows,j:j+filter_cols]
      output[i, j] = np.sum(region * filter)

  return output

def max_pool(matrix, pool_size, stride):
  matrix_rows, matrix_cols = matrix.shape
  output_rows = (matrix_rows - pool_size) // stride + 1
  output_cols = (matrix_cols - pool_size) // stride + 1
  output = np.zeros((output_rows, output_cols))
  for i in range(0,output_rows,stride):
    for j in range(0,output_cols,stride):
      region = matrix[i:i+pool_size,j:j+pool_size]
      output[i, j] = np.max(region)
  return output

filter = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])
stride = 1
a = np.random.randint(0, 2, size=(5, 5))
output_matrix = conv(a, filter, stride)
m_pool = max_pool(output_matrix, 2, 2)
print("input matrix\n",a)
print("\nConvolved Matrix:\n", output_matrix)
print("\nMax Pooling Matrix:\n", m_pool)

input matrix
 [[1 1 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 1 1 0 0]
 [1 1 0 1 1]]

Convolved Matrix:
 [[1. 1. 0.]
 [2. 0. 0.]
 [1. 3. 1.]]

Max Pooling Matrix:
 [[2.]]
